2025-09-11 09:27:42,981 [ERROR] test - logger._log:342 - エラーメッセージ
2025-09-11 09:27:42,981 [FATAL] test - logger._log:342 - 致命的エラーメッセージ
2025-09-11 09:27:42,981 [ERROR] test - logger._log:342 - このエラーは表示される
2025-09-11 09:27:42,981 [FATAL] test - logger._log:342 - この致命的エラーは表示される
2025-09-11 09:27:42,983 [ERROR] test - logger._log:342 - 例外が発生しました
Traceback (most recent call last):
  File "C:\prj\discord-mkmk-vc-tracker\src\logger.py", line 472, in <module>
    raise ValueError("テスト例外")
ValueError: テスト例外
